### ISSUE TITLE
Error when use docker-compose up

### ISSUE THREAD

**Issue by candidosales** [hyperledger/sawtooth-hyper-directory#6]
ERROR: Service 'server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder186586033/server/config.py: no such file or directory

Using pip 9.0.1 and python 2.7

**Comment by chrisspanton** [comment]
The code posted here includes only config.py.example - per README.md you need to make appropriate changes to the file and rename as config.py. Should solve your issue.
